CREATE TABLE [dbo].[Addresses] (
    [AddressId]      INT            NOT NULL,
    [UserId]         INT            NULL,
    [SupplierId]     INT            NULL,
    [AddressTypeId]  INT            NULL,
    [IsCompany]      BIT            NULL,
    [CompanyName]    VARCHAR (500)  NULL,
    [TaxNumber]      VARCHAR (50)   NULL,
    [TaxOffice]      VARCHAR (500)  NULL,
    [ShippingPerson] VARCHAR (100)  NULL,
    [ShippingPhone]  CHAR (10)      NULL,
    [IdentityNumber] CHAR (11)      NULL,
    [Name]           VARCHAR (50)   NULL,
    [AddressLine1]   VARCHAR (1000) NULL,
    [AddressLine2]   VARCHAR (1000) NULL,
    [District]       VARCHAR (1000) NULL,
    [County]         VARCHAR (1000) NULL,
    [City]           VARCHAR (1000) NULL,
    [GeoZone]        VARCHAR (1000) NULL,
    [Country]        VARCHAR (1000) NULL,
    [PostalCode]     CHAR (5)       NULL,
    [FullAddress]    VARCHAR (MAX)  NULL,
    [IsValid]        BIT            NULL,
    [Comment]        VARCHAR (MAX)  NULL,
    [LastUpdatedBy]  INT            NULL,
    [CreatedOn]      DATETIME       NULL,
    [UpdatedOn]      DATETIME       NULL,
    [DeletedOn]      DATETIME       NULL
);

