CREATE TABLE [dbo].[GiftCards] (
    [GiftCardId]             INT             NOT NULL,
    [GiftCardTypeId]         INT             NULL,
    [Name]                   VARCHAR (500)   NULL,
    [Description]            VARCHAR (MAX)   NULL,
    [GiftCardCode]           VARCHAR (50)    NULL,
    [SenderCustomerId]       INT             NULL,
    [SenderName]             VARCHAR (100)   NULL,
    [SenderPhone]            CHAR (10)       NULL,
    [SenderEmail]            VARCHAR (255)   NULL,
    [SenderMessage]          VARCHAR (MAX)   NULL,
    [RecipientCustomerId]    INT             NULL,
    [RecipientName]          VARCHAR (100)   NULL,
    [RecipientPhone]         CHAR (10)       NULL,
    [RecipientEmail]         VARCHAR (255)   NULL,
    [StartedOn]              DATETIME        NULL,
    [EndedOn]                DATETIME        NULL,
    [IsActive]               BIT             NULL,
    [IsNotified]             BIT             NULL,
    [IsLimited]              BIT             NULL,
    [MinimumBasketAmount]    DECIMAL (18, 2) NULL,
    [MinimumBasketItemCount] INT             NULL,
    [Comment]                VARCHAR (MAX)   NULL,
    [LastUpdatedBy]          INT             NULL,
    [CreatedOn]              DATETIME        NULL,
    [UpdatedOn]              DATETIME        NULL,
    [DeletedOn]              DATETIME        NULL
);

