CREATE TABLE [dbo].[OrderDetails] (
    [OrderDetailId]                INT             NOT NULL,
    [OrderId]                      INT             NULL,
    [ProductId]                    INT             NULL,
    [Quantity]                     INT             NULL,
    [Price]                        DECIMAL (18, 2) NULL,
    [Amount]                       DECIMAL (18, 2) NULL,
    [DiscountedAmount]             DECIMAL (18, 2) NULL,
    [TaxRate]                      DECIMAL (18, 2) NULL,
    [TaxAmout]                     DECIMAL (18, 2) NULL,
    [ShippedOn]                    DATETIME        NULL,
    [pProductCategoryId]           INT             NULL,
    [pSupplierId]                  INT             NULL,
    [pBrandId]                     INT             NULL,
    [pProductTypeId]               INT             NULL,
    [pGender]                      CHAR (1)        NULL,
    [pName]                        VARCHAR (500)   NULL,
    [pSupplierDescription]         VARCHAR (MAX)   NULL,
    [pDescription]                 VARCHAR (MAX)   NULL,
    [pShortDescription]            VARCHAR (2000)  NULL,
    [pHtmlDescription]             VARCHAR (150)   NULL,
    [pUrlName]                     VARCHAR (500)   NULL,
    [pMarketPrice]                 DECIMAL (18, 2) NULL,
    [pPriceFromSupplier]           DECIMAL (18, 2) NULL,
    [pDiscountPercent]             INT             NULL,
    [pCommissionPercent]           INT             NULL,
    [pTaxPercent]                  DECIMAL (18)    NULL,
    [pBarcode]                     VARCHAR (50)    NULL,
    [pHasDifferentPriceForOptions] BIT             NULL,
    [DeletedOn]                    DATETIME        NULL,
    [Comment]                      VARCHAR (MAX)   NULL,
    [LastUpdatedBy]                INT             NULL,
    [CreatedOn]                    DATETIME        NULL,
    [UpdatedOn]                    DATETIME        NULL
);

