CREATE TABLE [dbo].[PaymentTransactions] (
    [PaymentId]             INT             NOT NULL,
    [OrderId]               INT             NOT NULL,
    [BankId]                INT             NOT NULL,
    [CreditCardTypeId]      INT             NOT NULL,
    [CreditCardId]          INT             NOT NULL,
    [PaymentTypeId]         INT             NOT NULL,
    [VPosOrderId]           VARCHAR (50)    NULL,
    [ResponseSource]        VARCHAR (50)    NULL,
    [ResponseCode]          CHAR (2)        NULL,
    [ResponseReasonCode]    CHAR (2)        NULL,
    [ResponseMessage]       VARCHAR (MAX)   NULL,
    [ResponseErrorMsg]      VARCHAR (MAX)   NULL,
    [ResponseSysErrMsg]     VARCHAR (MAX)   NULL,
    [RetrefNum]             VARCHAR (50)    NULL,
    [AuthCode]              VARCHAR (50)    NOT NULL,
    [BatchNum]              VARCHAR (50)    NULL,
    [SequenceNum]           VARCHAR (50)    NULL,
    [ProvDate]              DATETIME        NULL,
    [MaskedCardNumber]      VARCHAR (16)    NULL,
    [MaskedCardHolderName]  VARCHAR (50)    NULL,
    [HashData]              CHAR (40)       NULL,
    [PaymentRequestIp]      VARCHAR (50)    NULL,
    [CurrencyCode]          VARCHAR (5)     NULL,
    [InstalmentCount]       INT             NULL,
    [IsInstalmentBuying]    BIT             NULL,
    [IsPaidWithBonusPoints] BIT             NULL,
    [IsCompleted]           BIT             NULL,
    [BonusPointAmount]      DECIMAL (18, 2) NULL,
    [Amount]                DECIMAL (18, 2) NULL,
    [TotalAmount]           DECIMAL (18, 2) NOT NULL,
    [Comment]               VARCHAR (MAX)   NULL,
    [LastUpdatedBy]         INT             NOT NULL,
    [CreatedOn]             DATETIME        NOT NULL,
    [UpdatedOn]             DATETIME        NOT NULL,
    [DeletedOn]             DATETIME        NULL
);

