CREATE TABLE [dbo].[Products] (
    [ProductId]                   INT				NOT NULL,
    [ProductCategoryId]           INT				NULL,
    [SupplierId]                  INT				NULL,
    [BrandId]                     INT				NULL,
    [ProductTypeId]               INT				NULL,
    [Gender]                      CHAR (1)			NULL,
    [Name]                        VARCHAR (500)		NULL,
    [SupplierDescription]         VARCHAR (MAX)		NULL,
    [Description]                 VARCHAR (MAX)		NULL,
    [ShortDescriptioon]           VARCHAR (2000)	NULL,
    [HtmlDescription]             VARCHAR (150)		NULL,
    [UrlName]                     VARCHAR (500)		NULL,    
    [DiscountPercent]             INT				NULL,
    [CommissionPercent]           INT				NULL,    
	[TaxPercent]                  DECIMAL (18)		NULL,
	[Price]						  DECIMAL (18, 2)	NULL,
	[PriceMarket]				  DECIMAL (18, 2)	NULL,
    [PriceSupplier]				  DECIMAL (18, 2)	NULL,    
    [MaximumPurchaseCount]        INT				NULL,
    [IsActive]                    BIT				NULL,
    [IsFeatured]                  BIT				NULL,
    [IsOnVote]                    BIT				NULL,
    [VoteCount]                   INT				NULL,
    [Comment]                     VARCHAR (MAX)		NULL,
    [LastModifiedBy]              INT				NULL,
    [PublishedOn]                 DATETIME			NULL,
    [UpdateOn]                    DATETIME			NULL,
    [CreatedOn]                   DATETIME			NULL,
    [DeletedOn]                   DATETIME			NULL
);

