ALTER TABLE [dbo].[Affiliates]
    ADD CONSTRAINT [PK_Affilates] PRIMARY KEY CLUSTERED ([AffiliateId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

