ALTER TABLE [dbo].[Banks]
    ADD CONSTRAINT [PK_Banks] PRIMARY KEY CLUSTERED ([BankId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

