ALTER TABLE [dbo].[Brands]
    ADD CONSTRAINT [PK_Brands] PRIMARY KEY CLUSTERED ([BrandId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

