ALTER TABLE [dbo].[Cities]
    ADD CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED ([CityId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

