ALTER TABLE [dbo].[Countries]
    ADD CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED ([CountryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

