ALTER TABLE [dbo].[CreditCards]
    ADD CONSTRAINT [PK_CreditCards] PRIMARY KEY CLUSTERED ([CreditCardId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

