ALTER TABLE [dbo].[CampaignProducts]
    ADD CONSTRAINT [PK_CampaignProducts] PRIMARY KEY CLUSTERED ([CampaignProductId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

