ALTER TABLE [dbo].[GeoZones]
    ADD CONSTRAINT [PK_GeoZones] PRIMARY KEY CLUSTERED ([GeoZoneId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

