ALTER TABLE [dbo].[GiftCardTypes]
    ADD CONSTRAINT [PK_GiftCardTypes] PRIMARY KEY CLUSTERED ([GiftCardTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

