ALTER TABLE [dbo].[GiftCards]
    ADD CONSTRAINT [PK_GiftCards] PRIMARY KEY CLUSTERED ([GiftCardId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

