ALTER TABLE [dbo].[Logs]
    ADD CONSTRAINT [PK_Logs] PRIMARY KEY CLUSTERED ([LogId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

