ALTER TABLE [dbo].[LogEvents]
    ADD CONSTRAINT [PK_LogEvents] PRIMARY KEY CLUSTERED ([LogEventId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

