ALTER TABLE [dbo].[OrderStatuses]
    ADD CONSTRAINT [PK_OrderStatuses] PRIMARY KEY CLUSTERED ([OrderStatusId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

