ALTER TABLE [dbo].[ProductTypes]
    ADD CONSTRAINT [PK_ProductTypes] PRIMARY KEY CLUSTERED ([ProductTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

