ALTER TABLE [dbo].[ProductOptions]
    ADD CONSTRAINT [PK_ProductOptions] PRIMARY KEY CLUSTERED ([ProductOptionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

