ALTER TABLE [dbo].[ProductPriceHistories]
    ADD CONSTRAINT [PK_ProductPriceHistories] PRIMARY KEY CLUSTERED ([ProductPriceHistoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

