ALTER TABLE [dbo].[ProductMedias]
    ADD CONSTRAINT [PK_ProductMedias] PRIMARY KEY CLUSTERED ([ProductMediaId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

