ALTER TABLE [dbo].[ProductVoteHistories]
    ADD CONSTRAINT [PK_ProductVoteHistories] PRIMARY KEY CLUSTERED ([ProductVoteHistoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

