ALTER TABLE [dbo].[ProductOptionGroupMembers]
    ADD CONSTRAINT [PK_ProductOptionGroupMembers] PRIMARY KEY CLUSTERED ([ProductOptionGroupMemberId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

