ALTER TABLE [dbo].[Phones]
    ADD CONSTRAINT [PK_Phones] PRIMARY KEY CLUSTERED ([PhoneId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

