ALTER TABLE [dbo].[ProductCategories]
    ADD CONSTRAINT [PK_ProductCategories] PRIMARY KEY CLUSTERED ([ProductCategoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

