ALTER TABLE [dbo].[ProductOptionPrices]
    ADD CONSTRAINT [PK_ProductOptionPrices] PRIMARY KEY CLUSTERED ([ProductOptionPriceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

