ALTER TABLE [dbo].[ProductOptionGroups]
    ADD CONSTRAINT [PK_ProductOptionGroups] PRIMARY KEY CLUSTERED ([ProductOptionGroupId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

