ALTER TABLE [dbo].[PaymentTransactions]
    ADD CONSTRAINT [PK_Payments] PRIMARY KEY CLUSTERED ([PaymentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

