ALTER TABLE [dbo].[QueuedEmails]
    ADD CONSTRAINT [PK_QueuedEmails] PRIMARY KEY CLUSTERED ([QueuedEmailID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

