ALTER TABLE [dbo].[Shippings]
    ADD CONSTRAINT [PK_Shippings] PRIMARY KEY CLUSTERED ([ShippingId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

