ALTER TABLE [dbo].[SuppliersBrands]
    ADD CONSTRAINT [PK_SuppliersBrands] PRIMARY KEY CLUSTERED ([SuppliersBrandId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

